name: Actualizar

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    name: check, update and commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Python
        run: |
          python -m pip install --upgrade pip
          pip install pandas geopandas requests
      - name: Actualizar
        run: |
         ./resultados/datos/actualizar.py
         ./resultados/datos/preparar.py
      - name: Commit
        run: |
          git config --global user.email "elecciones2025@example.com"
          git config --global user.name "elecciones2025-bot"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "[ci] actualizaci√≥n de resultados"; git push -q "https://$GH_TOKEN@github.com/datosbolivia/elecciones2025.git" main)
